name: package-release

on:
  push:
    tags:
      - 'v*'


jobs:
  carvel-pihole-package-release:
    name: carvel-pihole package release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3.0.1

      - name: Install Carvel tools
        uses: vmware-tanzu/carvel-setup-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push updated Package to Github Container Registry
        run: |
          imgpkg push -b ghcr.io/${{ github.actor }}/carvel-pihole:${{ github.ref_name }} -f .
          imgpkg push -b ghcr.io/${{ github.actor }}/carvel-pihole:latest -f .